// lib/cities.ts

export const cities = [
  'new-york-ny',
  'los-angeles-ca',
  'chicago-il',
  'houston-tx',
  'phoenix-az',
  'philadelphia-pa',
  'san-antonio-tx',
  'san-diego-ca',
  'dallas-tx',
  'austin-tx',
  'jacksonville-fl',
  'fort-worth-tx',
  'columbus-oh',
  'charlotte-nc',
  'san-francisco-ca',
  'indianapolis-in',
  'seattle-wa',
  'denver-co',
  'washington-dc',
  'boston-ma',
  'nashville-tn',
  'atlanta-ga',
  'miami-fl',
  'orlando-fl',
  'tampa-fl',
  'las-vegas-nv',
  'detroit-mi',
  'minneapolis-mn',
  'st-louis-mo',
  'kansas-city-mo',
  'salt-lake-city-ut',
  'new-orleans-la',
  'pittsburgh-pa',
  'cincinnati-oh',
  'cleveland-oh',
  'buffalo-ny',
  'rochester-ny',
  'albany-ny',
  'long-island-ny',
  'brooklyn-ny',
  'queens-ny',
  'bronx-ny',
  'staten-island-ny',
  'jersey-city-nj',
  'newark-nj',
  'hoboken-nj',
  'trenton-nj',
  'hartford-ct',
  'new-haven-ct',
  'providence-ri',
  'portland-or',
  'sacramento-ca',
  'fresno-ca',
  'oakland-ca',
  'mesa-az',
  'tucson-az',
  'raleigh-nc',
  'richmond-va',
  'virginia-beach-va',
  'baltimore-md',
];

// Only the cities we actually sell in get indexed by Google. The rest stay
// live but noindex, so ~2,300 near-identical pages don't drag down the site.
// Add a city here once you're actively working that area.
export const INDEXED_CITIES = new Set<string>(['long-island-ny', 'queens-ny']);

export const SERVICES = [
  'hvac', 'electrical', 'plumbing', 'roofing', 'painting',
  'handyman', 'landscaping', 'cleaning', 'moving', 'locksmith',
  'fencing', 'concrete', 'flooring', 'siding', 'gutters',
  'pressure-washing', 'tree-service', 'pest-control', 'garage-door',
  'window-installation', 'drywall', 'demolition', 'excavation',
  'septic', 'paving', 'masonry', 'welding', 'insulation',
  'solar', 'pool-service', 'irrigation', 'appliance-repair',
  'chimney', 'waterproofing', 'foundation-repair', 'junk-removal',
  'carpet-cleaning', 'auto-detailing', 'towing',
];